name: 'Terraform CI/CD Pipeline'

on:
  push:
    branches: [ "main", "feature/secure-oidc-cicd" ] # We voegen hier tijdelijk je test-branch toe!
    paths-ignore:
      - 'README.md'
      - 'screenshots/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'screenshots/**'

# VERPLICHT VOOR OIDC: Dit geeft GitHub toestemming om een beveiligd inlogtoken te claimen bij Azure
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform Validation & Deployment'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    # De "Pro" methode: ARM_CLIENT_SECRET is hier permanent verwijderd!
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.5"

    - name: Terraform Format & Validate
      run: |
        terraform fmt -check
        terraform init -backend=false
        terraform validate

    # DEVSECOPS: We scannen je hub-spoke netwerkcode op beveiligingslekken vóór de planfase
    - name: Run Trivy Security Scanner (IAC)
      uses: aquasecurity/trivy-action@v0.28.0
      with:
        scan-type: 'config'
        hide-progress: false
        format: 'cli'
        exit-code: '1' # De pipeline stopt direct als er een high/critical kwetsbaarheid is!
        severity: 'HIGH,CRITICAL'

    - name: Terraform Init Remote
      run: terraform init

    # We slaan het planbestand op zodat we 100% consistentie houden
    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    # De echte Pro-beveiliging: Alleen apply uitvoeren als we écht op main pushen. 
    # Op jouw test-branch stopt de pipeline dus automatisch na de 'Plan' stap!
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve tfplan
